# Generated by Django 4.1.3 on 2022-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Название')),
                ('email', models.EmailField(max_length=45, verbose_name='Почта')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('completion_at', models.DateField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=30, verbose_name='Статус')),
            ],
        ),
    ]
